name: Deploy Snap

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Snap
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: yarn --immutable
      - name: Production Deployment
        run: |
          VERSION=$(node -p "require('./packages/snap/package.json').version")

          npm --prefix ./packages/snap version --new-version "${VERSION}" --no-git-tag-version --allow-same-version
          yarn workspace @consensys/linea-voyager build

          npm publish ./packages/snap --tag latest --access public > /dev/null 2>&1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
