name: Publish site to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  publish-site-to-gh-pages:
    name: Publish site to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Prepare for deployment
        run: |
          echo "voyager-snap.linea.build" > packages/site/src/CNAME
          echo "User-Agent: *" > packages/site/src/robots.txt
          echo "Disallow: /" >> packages/site/src/robots.txt
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './packages/site/src'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
